### ISSUE TITLE
Requested Skill Has Not Been Configured to Support Dialogues Yet

### ISSUE THREAD

**Issue by nfragnito** [alexa/skill-sample-nodejs-decision-tree#28]
I followed the instructions listed, copied and pasted the code provided, and then received the error below. This only happens say anything to open the RecommendationIntent such as "start my career."  If I say "couch potato" it continues just fine into the CouchPotatoIntent. 

Invalid Directive
Decision Tree 3
Request Identifier: amzn1.echo-api.request.de7e24b9-674b-4e94-80cd-37c4f6e4af0f The requested skill has not been configured to support dialogs yet. Please update the skill's configuration from the Developer Console

Does anyone understand why this would happen or know how to solve?

**Comment by SleepyDeveloper** [comment]
Your lambda function is returning dialog directives, but your Interaction Model can't receive them because you don't have any required slots. 

You'll need to make the slots required and rebuild in order to fix the problem.

**Comment by nfragnito** [comment]
Thanks for the response. So the code lays out all of the slots and then it auto-populates the slots in the Skill Builder. I went back and checked the box to make them required. Then I had to input prompts and utterances. Those were already in the code, but I went ahead and put them in again. Then I rebuilt the model and tested. The first time it actually asked the first question of RecommendationIntent, then I received the same error after I answered. Then I went back to the Skill Builder and all of the slots had reverted back to not required. 

So I tried the same thing again, this time also manually going into Slot Types and adding the same synonyms. After testing, I received the same error, never entering RecommendationIntent.

What did I do wrong?

I guess I don't understand why this extra step isn't included in the instructions and why if we write the code, we have to also manually enter redundant information.

**Comment by SleepyDeveloper** [comment]
@nfragnito 

While you can override the prompts in your code using the `elicitSlot` directive, your interaction model needs to indicate that the intent supports dialog management otherwise the Alexa service will throw an error because it received unexpected directives from your skill.

Are you still encountering issues with this? If so please attach the error message so I can further assist you.

Thanks

**Comment by SleepyDeveloper** [comment]
@nfragnito Closing this issue. If you are still having problems please reopen.
