### ISSUE TITLE
Request to skill endpoint

### ISSUE THREAD

**Issue by kumarks102** [alexa/skill-sample-nodejs-decision-tree#32]
After follwing all the steps and when i execute the command

ask simulate -l en-US -t "start decision tree"

it starts properly and i get the SUCCESSFUL message, but at last after executing i get this error

Request to skill endpoint resulted in an error.

Here is the full execution,
D:\npm\skill-sample-nodejs-decision-tree>ask simulate -l en-US -t "start decision tree"
✓ Simulation created for simulation id: 8088a33f-4357-48a8-a0a1-5f842ff6a204
\ Waiting for simulation response{
  "id": "8088a33f-4357-48a8-a0a1-5f842ff6a204",
  "status": "SUCCESSFUL",
  "result": {
    "skillExecutionInfo": {
      "invocationRequest": {
        "endpoint": "**arn:aws:lambda:us-east-1:060799683295:function:fact-skill**",
        "body": {
          "version": "1.0",
          "session": {
            "new": true,
            "sessionId": "amzn1.echo-api.session.172a8c21-2e7a-4ce2-8b20-42a8492100d4",
            "application": {
              "applicationId": "amzn1.ask.skill.241294f4-f64e-464b-9cfc-4556a297025a"
            },
            "user": {
              "userId": "amzn1.ask.account.AHXJNG75SMLQH7LSXUK55HZVWOZ6IAA57XZZSDL2ZENR5B24TKN4EPKZMD6OIO2YE57X23PTZK4MVR2S45COMMUZO6CH5UMYNWSVJ6RN4M2GRI7IBY3Y3CICF55YOJJOXNVUEDCEXBUIJK4IKAFWCDUR7EUJ2XIARH4COAL2EC5DTPCM3HF7GP5ZRWOPAYJFYW5Q4VYE2RTA5GA"
            }
          },
          "context": {
            "Display": {},
            "System": {
              "application": {
                "applicationId": "amzn1.ask.skill.241294f4-f64e-464b-9cfc-4556a297025a"
              },
              "user": {
                "userId": "amzn1.ask.account.AHXJNG75SMLQH7LSXUK55HZVWOZ6IAA57XZZSDL2ZENR5B24TKN4EPKZMD6OIO2YE57X23PTZK4MVR2S45COMMUZO6CH5UMYNWSVJ6RN4M2GRI7IBY3Y3CICF55YOJJOXNVUEDCEXBUIJK4IKAFWCDUR7EUJ2XIARH4COAL2EC5DTPCM3HF7GP5ZRWOPAYJFYW5Q4VYE2RTA5GA"
              },
              "device": {
                "deviceId": "amzn1.ask.device.AGMHRDUAIUNAMMTFNBEOLCL36K7SPUP454HN63C4M75YMGFYC2W5YRB7ZUTCONCVPW5G7YPTQCHWIOPHXW55BDITO5W7RR4AV3SESVKMTTCWSVW5EK3HTG75CELEOUW7K6PTYRQP45634ROCH47PO5BAPRMA",
                "supportedInterfaces": {
                  "AudioPlayer": {},
                  "Display": {
                    "templateVersion": "1.0",
                    "markupVersion": "1.0"
                  }
                }
              },
              "apiEndpoint": "https://api.amazonalexa.com",
              "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjI0MTI5NGY0LWY2NGUtNDY0Yi05Y2ZjLTQ1NTZhMjk3MDI1YSIsImV4cCI6MTUyNTg2MzUxOSwiaWF0IjoxNTI1ODU5OTE5LCJuYmYiOjE1MjU4NTk5MTksInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUdNSFJEVUFJVU5BTU1URk5CRU9MQ0wzNks3U1BVUDQ1NEhONjNDNE03NVlNR0ZZQzJXNVlSQjdaVVRDT05DVlBXNUc3WVBUUUNIV0lPUEhYVzU1QkRJVE81VzdSUjRBVjNTRVNWS01UVENXU1ZXNUVLM0hURzc1Q0VMRU9VVzdLNlBUWVJRUDQ1NjM0Uk9DSDQ3UE81QkFQUk1BIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUhYSk5HNzVTTUxRSDdMU1hVSzU1SFpWV09aNklBQTU3WFpaU0RMMlpFTlI1QjI0VEtONEVQS1pNRDZPSU8yWUU1N1gyM1BUWks0TVZSMlM0NUNPTU1VWk82Q0g1VU1ZTldTVko2Uk40TTJHUkk3SUJZM1kzQ0lDRjU1WU9KSk9YTlZVRURDRVhCVUlKSzRJS0FGV0NEVVI3RVVKMlhJQVJINENPQUwyRUM1RFRQQ00zSEY3R1A1WlJXT1BBWUpGWVc1UTRWWUUyUlRBNUdBIn19.VpFsw5R23HzaHu4iX4U3kIQk5KvjjJ9ZWOJ-HPnItnxY2VUZut2rQQP-zyuOw5KKRX5-W-qCvYZsqrAhcXpJqVPxltv7uFuxY5ExESq0Wue4lDnSfMo8uwLsRBUfE606WWD5gP9FZWBCXBf0r3QvPM4s4vTuM1t5GV48PmG3zpuQtAQUyxVee4sqwZh3TK9-s_M0YHvwG-Z9aH7sGSyKxr97PMMtM8Fr76MlDYLRaR6Hfd7VEl2JWbC4BHE_fcr_v6d6SxMeEDtUvNzI341ftOE473gaFrbDhWLnSknj9lzDx9LGCuX6RlRPdfd7V5XuQdQvAYvn5PQkc1giwu3Big"
            }
          },
          "request": {
            "type": "LaunchRequest",
            "requestId": "amzn1.echo-api.request.eca08966-0d52-4a4d-b5bd-8913c300d388",
            "timestamp": "2018-05-09T09:58:39Z",
            "locale": "en-US",
            "shouldLinkResultBeReturned": false
          }
        }
      },
      "metrics": {
        "skillExecutionTimeInMilliseconds": 43
      }
    },
    "error": {
      "message": "Request to skill endpoint resulted in an error."
    }
  }
}

I see the end point is different but i went and changed manually still the same problem comes.

**Comment by franklin-lobb** [comment]
The error being thrown does not occur in Node.js 8.10.  Is it correct that you used the ask-cli to create the Lambda function, and is it using Node.js 6.10?

The latest version of the ask-cli creates functions using Node.js 8.10.  As of today ```ask --version``` returns 1.3.1.  If you're on an earlier version, ask-cli may create the function using an earlier version of Node.js.  Run ```npm update -g ask-cli ``` to get the latest version of the ASK CLI.

If you update your ask-cli before deploying the first time, it will work correctly. 

If you want to fix a function you've already deployed, you have a couple of options.  Since the ask-cli does not modify the runtime for an existing function, you can fix an existing function by going into the Lambda console and changing the runtime to Node.js 8.10.  (Don't forget to click Save!)

Alternatively, you can remove the comma from this line: https://github.com/alexa/skill-sample-nodejs-decision-tree/blob/0c193888a0192bc6dd059e87df93443990718942/lambda/custom/index.js#L312

**Comment by donfranke** [comment]
I am running npm 5.8.0 on Ubuntu/Windows 10 and ASK CLI version 1.4.0 and the Lambda function for the decision-tree template also was created using Node.js 6.10 by default. Changing it to 8.10 in the Lambda UI fixed it, but can the template be corrected to use the right version of Node.js by default? I don't see an option to set this in any of the template files unfortunately--perhaps this is a feature request.

**Comment by franklin-lobb** [comment]
I tested it out and v1.3.1 created Node.js 8.10 functions and v1.4.0 creates Node.js 6.10.  Currently there's no way to specify the version in the template so you'll have to manually change it for now.

**Comment by franklin-lobb** [comment]
ask-cli version 1.4.1 was just released which returns to creating Node 8 functions.
