### ISSUE TITLE
Cannot configure test events

### ISSUE THREAD

**Issue by vnyk** [alexa/skill-sample-nodejs-decision-tree#34]
I have created a test event and copied and pasted my json input from test emulator to aws Configure session.
![captureamzn](https://user-images.githubusercontent.com/25143052/41221288-5321f152-6d81-11e8-809d-967cbe5a0180.PNG)

I pasted above code here

![captureaws](https://user-images.githubusercontent.com/25143052/41221314-63eb1ed2-6d81-11e8-93ce-4b661e245739.PNG)

Then I am getting the following error

Execution result: failed(logs)
Details`{
  "errorMessage": "Unexpected token )",
  "errorType": "SyntaxError",
  "stackTrace": [
    "createScript (vm.js:56:10)",
    "Object.runInThisContext (vm.js:97:10)",
    "Module._compile (module.js:542:28)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)"
  ]
}`

`ntlage
Execution result: failed(logs)
Details
The area below shows the result returned by your function execution. Learn more about returning results from your function.
{
  "errorMessage": "Unexpected token )",
  "errorType": "SyntaxError",
  "stackTrace": [
    "createScript (vm.js:56:10)",
    "Object.runInThisContext (vm.js:97:10)",
    "Module._compile (module.js:542:28)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)"
  ]
}
Summary
Code SHA-256
0AUAT9EuCPEGpiv23ccgwTY8+UeQv3y0QCrVSQeLbWs=
Request ID
d3f7856e-6d52-11e8-80b7-5539aaf920a9
Duration
16.40 ms
Billed duration
100 ms
Resources configured
128 MB
Max memory used
20 MB
Log output
The area below shows the logging calls in your code. These correspond to a single row within the CloudWatch log group corresponding to this Lambda function. Click here to view the CloudWatch log group.
START RequestId: d3f7856e-6d52-11e8-80b7-5539aaf920a9 Version: $LATEST
Syntax error in module 'index': SyntaxError
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
END RequestId: d3f7856e-6d52-11e8-80b7-5539aaf920a9
REPORT RequestId: d3f7856e-6d52-11e8-80b7-5539aaf920a9	Duration: 16.40 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 20 MB`

Is this error because I am using english(IN) for development

**Comment by vnyk** [comment]
Resolved it my self, thanks

**Comment by ghost** [comment]
> Resolved it my self, thanks

can you tell me how you resolved it,since i am too facing the same issue
