### ISSUE TITLE
index_template.js not found

### ISSUE THREAD

**Issue by Jaskaran12** [alexa/skill-sample-nodejs-decision-tree#36]
Clicking on the link of page customisation (on the link Index_template.js) is showing Page not found.

**Comment by Wizzarro** [comment]
I have same problem, did you solve it?

**Comment by samueldowd** [comment]
I never got an answer and ended up just giving up. I think this may be an old tutorial for a deprecated way of creating a skill like this. Unfortunately it seems like it is a much easier way than the new way they have gone with.

**Comment by Wizzarro** [comment]
Thanks for replying!

**Comment by franklin-lobb** [comment]
Sorry I missed this previously.  Those portions of the instructions were from the version of this skill prior to dialog management.  I've removed the bad links and outdated instructions.
