### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by jilusan** [alexa/skill-sample-nodejs-decision-tree#44]
Hi,
We will appreciate if the code and model interaction will come with some explanation. I could not find it anywhere. The concept of decision tree seems interesting. Thanks!

**Comment by Ilyt00** [comment]
Please, check out this post [Alexa-Decision-tree](https://developer.amazon.com/blogs/alexa/post/5b0efd02-0ed0-42d5-b922-5ee594d30a38/new-alexa-skills-kit-template-build-an-alexa-decision-tree-skill) to learn more about how you can use the updated sample skill template for a basic decision tree skill
